### ISSUE TITLE
Make meaningful inheritance possible, change private properties to protected

### ISSUE THREAD

**Issue by ampaze** [ptrstovka/letsencrypt-php#2]
Thanks for this cool library.

I want to override `LEOrder::verifyDNSChallenge` which is currently not possible, as the method and the used properties are private. 

That is why I want to change all `private` declarations to `protected`.

I can provide a PR for this.

## Context

I want to combine this Let's Encrypt Client with https://github.com/yswery/PHP-DNS-SERVER.
Right now the following loop is what I want to modify, but the particular change I need might evolve.
```php
while ($auth->status == 'pending') {
    $this->log->notice("DNS challenge for $identifier valid - waiting for confirmation");
    $this->sleep->for(1);
    $auth->updateData();
}
```

**Comment by ptrstovka** [comment]
Good, I think it would be okay. 
Please provide a PR, I am happy to merge. :)

**Comment by ampaze** [comment]
Awesome! Thanks.

**Comment by ampaze** [comment]
Could you make a new release for the recent changes?

**Comment by ptrstovka** [comment]
Just tagged `2.0` 👍
