### ISSUE TITLE
Unauthenticated resource GET was deprecated by Let's Encrypt

### ISSUE THREAD

**Issue by ampaze** [ptrstovka/letsencrypt-php#5]
Because of this I am unable to use the Staging API, more details here:

https://community.letsencrypt.org/t/acme-v2-scheduled-deprecation-of-unauthenticated-resource-gets/74380/4

Also the Production API will follow on November 1st, 2020.

This is how the error looks

```
 [GuzzleHttp\Exception\ClientException (405)]                                                                                                    
  Client error: `GET https://acme-staging-v02.api.letsencrypt.org/acme/order/xxxxx/xxxx` resulted in a `405 Method Not Allowed` response:  
  {                                                                                                                                               
    "type": "urn:ietf:params:acme:error:malformed",                                                                                               
    "detail": "Method not allowed",                                                                                                               
    "status": 405                                                                                                                                 
  }

**Comment by ptrstovka** [comment]
Thanks for reporting. For now I don't have much time for looking into it but definitely need do something until 1st November. I would accept a PR for that.

**Comment by ampaze** [comment]
I tried to fix it by changing `get` to `post ` and allowing the empty string as payload. But that was not enough to make Let's Encrypt happy.

With my limited knowledge of the protocol I will see what I can do.
