### ISSUE TITLE
Is it necessary to regenerate the key pair for renewal?

### ISSUE THREAD

**Issue by ampaze** [ptrstovka/letsencrypt-php#9]
Is there a reason for always creating a new key pair when renewing or creating a new order? 

## Context

As we want to distribute the certificate across multiple servers, it would be beneficial if the private key wouldn't change, when a certificate is renewed. This way the certificate can be downloaded by simply using a normal https connection between the servers.

Could this be made configurable?

**Comment by ptrstovka** [comment]
Hi,
as far as I know there is no reason for that. I didn't ever found a use case where this behaviour would be a problem.
I think we can make it somehow configurable.
Would you like to work on that feature?
Do you want to be a collaborator on this project? 
Currently I don't have much time to work on the library so I would really appreciate any kind of collaboration.

**Comment by ampaze** [comment]
Yes I will try to implement this.
Being collaborator sounds cool 😊  but I think for now it would be beneficial if we stick to the PR route and you can look over my proposed changes, when you find a bit of time.
